[project]
name = "mac-roman-decoder"
version = "0.1.2"
description = "Decodes and encodes using the Mac Roman character set, the default encoding for classic Mac OS."
requires-python = ">=3.10"
dependencies = []
readme = "README.md"

[build-system]
requires = ["setuptools>=68"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["src"]
